AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPCId:
    Type: String
    Description: The ID of the VPC (from main stack)
  PublicSubnet1Id:
    Type: String
    Description: The ID of the public subnet (from main stack)
  DatabaseEndpoint:
    Type: String
    Description: The endpoint of the RDS database (from main stack)

Resources:
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow HTTP and HTTPS traffic to the web server
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: WebServerSecurityGroup

  WebServerInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-01816d07b1128cd2d
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          SubnetId: !Ref PublicSubnet1Id
          GroupSet:
            - !Ref WebServerSecurityGroup
      Tags:
        - Key: Name
          Value: WebServerInstance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd php php-mysqlnd
          systemctl start httpd
          systemctl enable httpd

Outputs:
  WebServerPublicIP:
    Description: The public IP address of the web server
    Value: !GetAtt WebServerInstance.PublicIp
